Update test.audit-action.yaml

diff --git a/.github/workflows/test.audit-action.yaml b/.github/workflows/test.audit-action.yaml
--- a/.github/workflows/test.audit-action.yaml
+++ b/.github/workflows/test.audit-action.yaml
@@ -15,9 +15,9 @@ jobs:
         id: longrunner
         continue-on-error: true
         timeout-minutes: 1 # Times out after 1 minute
-        run: sleep 90
+        run: sleep 90 || echo 'echo "::set-output name=failure_reason::Script failed due to something random"' # Set your output error if your script fails. Include useful message
       - name: check previuos step
-        run: "[ '${{ steps.longrunner.outcome }}' == 'cancelled' ] &&  echo 'Step cancelled' || echo 'Status Found ${{ steps.longrunner.outcome }}'"
+        run: "[ -n '${{ steps.longrunner.outputs.failure_reason }}' ] &&  echo '::error::${{ steps.longrunner.outputs.failure_reason }}' && exit 1"
       - name: Use the action
         id: npm-audit-action
         uses: ./.github/actions/npm-audit-action
